### ISSUE TITLE
app.css 引入 common.css位置错误

### ISSUE THREAD

**Issue by yinpeng633** [NervJS/taro-plugin-platform-xhs#12]
参考小红书的issue，需要把app.css里 最下方的@import "./common.css";  移动到最上方，才能让common.css正常引入。
<img width="663" alt="image" src="https://user-images.githubusercontent.com/4269654/194699004-5642d51b-ee45-432e-9a55-14d339217af2.png">

**Comment by hhuwc** [comment]
请将插件更新到 @tarojs/plugin-platform-xhs@1.2.2
