### ISSUE TITLE
1.0.0 一直报警告

### ISSUE THREAD

**Issue by xf079** [NervJS/taro-plugin-platform-xhs#13]
![image](https://user-images.githubusercontent.com/63334662/195784966-7201e2e3-ac2e-4d5e-b43f-830c3611ae73.png)

**Comment by WeiJietao** [comment]
![截屏2022-10-14 下午4 00 05](https://user-images.githubusercontent.com/18640419/195794563-59b1ebf2-b6ad-4eb3-ae51-359f5d7d9a02.png)

打印了下，发现此处event会捕捉到"{currentTarget:undefined, isTrusted:true}"这样的数据，我手动把node_modules里的"[Taro modifyMpEvent hook Error]"去掉了，但不清楚这个报错会给页面带来什么副作用，还麻烦官方定位修复下。。

**Comment by Hubmeat** [comment]
给下复现代码呢？我们协助排查下根因

**Comment by hhuwc** [comment]
请将插件更新到 @tarojs/plugin-platform-xhs@1.2.2
