### ISSUE TITLE
1.0.0 swiper 手势失效，滑动不会自动滚动到下一页

### ISSUE THREAD

**Issue by xf079** [NervJS/taro-plugin-platform-xhs#14]
https://user-images.githubusercontent.com/63334662/195795025-972979f0-f32d-454b-b0b9-e9d1f58b3e07.mp4

**Comment by Hubmeat** [comment]
看起来是屏幕手势事件影响导致的，麻烦给下可稳定复现的 demo 把，否则不好排查原因
