### ISSUE TITLE
1.0.0 使用原生组件写法报错

### ISSUE THREAD

**Issue by WeiJietao** [NervJS/taro-plugin-platform-xhs#15]
![截屏2022-10-14 下午4 40 08](https://user-images.githubusercontent.com/18640419/195802794-d11337d6-0cc2-47e3-9eb8-210589fb7efb.png)

如上图，看样子好像缺少 xhsml 这种 loader？

**Comment by hhuwc** [comment]
请将插件更新到 @tarojs/plugin-platform-xhs@1.2.2
