### ISSUE TITLE
taro4.0.7，使用1.2.1最新插件 页面白屏，提示Template undefined is not found in base.xhsml 

### ISSUE THREAD

**Issue by xixihhhh** [NervJS/taro-plugin-platform-xhs#25]
转小红书小程序提示Template undefined is not found in base.xhsml

https://github.com/xixihhhh/taro-4.0.7-xhs

clone代码，跑dev:xhs，然后页面白屏无法正常预览，使用官方的初始化代码，什么都没加，1.2.1版本的小红书插件

**Comment by hhuwc** [comment]
tarojs-plugin-platform-xhs@1.2.2

你可以先使用这个临时版本，等到京东的兄弟们 发正式版本，你可以切回来 @tarojs/plugin-platform-xhs@1.2.2

记得要把 config 中的 plugins 名字也改了

**Comment by hhuwc** [comment]
请将插件更新到 @tarojs/plugin-platform-xhs@1.2.2
