### ISSUE TITLE
Taro转换成小红书小程序后 复制链接能成功 但 onCopyUrl 无法触发

### ISSUE THREAD

**Issue by pistachio-yaya** [NervJS/taro-plugin-platform-xhs#29]
希望近期可以处理

**Comment by hhuwc** [comment]
可以先试试 tarojs-plugin-platform-xhs  版本 1.2.2-beta.1   ，注意是 tarojs-plugin-platform-xhs  不是 @tarojs/plugin-platform-xhs 等你确认没问题后 我们会发正式版本

**Comment by pistachio-yaya** [comment]
目前没有拉到 1.2.2-beta.1 的版本 只有 1.2.2-beta.0


> 可以先试试 tarojs-plugin-platform-xhs 版本 1.2.2-beta.1 ，注意是 tarojs-plugin-platform-xhs 不是 @tarojs/plugin-platform-xhs 等你确认没问题后 我们会发正式版本

**Comment by hhuwc** [comment]
好的收到，后面会发正式版后通知你更改

**Comment by pistachio-yaya** [comment]
非常感谢 ❤️




喵酱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NervJS/taro-plugin-platform-xhs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月29日(星期五) 上午10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NervJS/taro-plugin-platform-xhs] Taro转换成小红书小程序后 复制链接能成功 但 onCopyUrl 无法触发 (Issue #29)





 
好的收到，后面会发正式版后通知你更改

**Comment by hhuwc** [comment]
请将插件更新到 @tarojs/plugin-platform-xhs@1.2.2

**Comment by pistachio-yaya** [comment]
实测可用 再次感谢




喵酱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NervJS/taro-plugin-platform-xhs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月2日(星期一) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NervJS/taro-plugin-platform-xhs] Taro转换成小红书小程序后 复制链接能成功 但 onCopyUrl 无法触发 (Issue #29)





 
请将插件更新到 @***@***.***
